"""Build the images of our own services (services/*) and push them to ECR.

Run from the repository root after `tofu apply` in infra/, with AWS_PROFILE set:

    uv run scripts/push_images.py

With a named AWS profile instead of the AWS_PROFILE variable:

    uv run scripts/push_images.py --profile NAME

Only build, without AWS (no login, no push), e.g. to check that the Dockerfiles still build:

    uv run scripts/push_images.py --build-only

The image tag is the service version from its pyproject.toml. The script also writes
apps/ai-assistant/registry/kustomization.yaml (git-ignored): a Kustomize component that
points the manifests at your account's ECR, so no account ID is stored in the repo.
"""

import argparse
import base64
import shutil
import subprocess
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path

import boto3
import yaml

REPOSITORY_PREFIX = "eks-incident-lab"

REPO_ROOT = Path(__file__).resolve().parent.parent
SERVICES_DIR = REPO_ROOT / "services"
REGISTRY_COMPONENT = REPO_ROOT / "apps" / "ai-assistant" / "registry" / "kustomization.yaml"


@dataclass(frozen=True)
class Service:
    name: str
    directory: Path
    version: str


def local_image(service: Service) -> str:
    return f"{REPOSITORY_PREFIX}/{service.name}:{service.version}"


@dataclass(frozen=True)
class Registry:
    host: str

    def repository(self, service: Service) -> str:
        return f"{self.host}/{REPOSITORY_PREFIX}/{service.name}"

    def image(self, service: Service) -> str:
        return f"{self.repository(service)}:{service.version}"


def find_services() -> list[Service]:
    services = []
    for pyproject in sorted(SERVICES_DIR.glob("*/pyproject.toml")):
        project = tomllib.loads(pyproject.read_text(encoding="utf-8"))["project"]
        services.append(Service(project["name"], pyproject.parent, project["version"]))
    return services


def find_registry(session: boto3.Session) -> Registry:
    if session.region_name is None:
        sys.exit("No AWS region: set it in your AWS profile or in AWS_REGION.")
    account_id = session.client("sts").get_caller_identity()["Account"]
    return Registry(f"{account_id}.dkr.ecr.{session.region_name}.amazonaws.com")


def write_registry_component(registry: Registry, services: list[Service]) -> None:
    component = {
        "apiVersion": "kustomize.config.k8s.io/v1alpha1",
        "kind": "Component",
        "images": [
            {"name": service.name, "newName": registry.repository(service), "newTag": service.version}
            for service in services
        ],
    }
    REGISTRY_COMPONENT.parent.mkdir(exist_ok=True)
    header = "# Generated by scripts/push_images.py. Do not edit, do not commit.\n"
    REGISTRY_COMPONENT.write_text(header + yaml.safe_dump(component, sort_keys=False), encoding="utf-8")


def run(command: list[str], stdin: str | None = None) -> str:
    executable = shutil.which(command[0]) or command[0]
    # Docker prints UTF-8 (BuildKit progress); without an explicit encoding Windows decodes it as cp1250.
    result = subprocess.run([executable, *command[1:]], input=stdin, capture_output=True,
                            text=True, encoding="utf-8", errors="replace")
    if result.returncode != 0:
        sys.exit(f"Command failed: {' '.join(command)}\n{result.stderr}")
    return result.stdout


def docker_login(session: boto3.Session, registry: Registry) -> None:
    # boto3 instead of the aws CLI: the CLI may live in another Python than the one `uv run` puts on PATH.
    token = session.client("ecr").get_authorization_token()["authorizationData"][0]["authorizationToken"]
    username, password = base64.b64decode(token).decode().split(":", 1)
    run(["docker", "login", "--username", username, "--password-stdin", registry.host], stdin=password)


def build(service: Service, image: str) -> None:
    print(f"Building {image}")
    run(["docker", "build", "--tag", image, str(service.directory)])


def build_locally(services: list[Service]) -> None:
    for service in services:
        build(service, local_image(service))
    print("Done. Images built locally; nothing pushed.")


def build_and_push(services: list[Service], profile: str | None = None) -> None:
    session = boto3.Session(profile_name=profile)
    registry = find_registry(session)
    write_registry_component(registry, services)
    docker_login(session, registry)
    for service in services:
        image = registry.image(service)
        build(service, image)
        print(f"Pushing  {image}")
        run(["docker", "push", image])
    print(f"Done. Image references written to {REGISTRY_COMPONENT.relative_to(REPO_ROOT)}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build service images and push them to ECR.")
    parser.add_argument("--build-only", action="store_true",
                        help="build the images locally, without AWS: no login, no push, no image references")
    parser.add_argument("--profile", help="AWS profile to use (default: the AWS_PROFILE variable)")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    services = find_services()
    if args.build_only:
        build_locally(services)
    else:
        build_and_push(services, args.profile)


if __name__ == "__main__":
    main()
