apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base

namePrefix: llm-rate-limit-recover-

patches:
  - target:
      kind: Job
      name: chaos-request
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: ["--fail", "--silent", "--show-error", "--request", "DELETE", "http://llm-gateway.ai-assistant.svc/chaos/status"]
